server:
  port: 8080
  servlet:
    context-path: /qwer
    development: true

spring:
  #สพิด
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    type: com.alibaba.druid.pool.DruidDataSource

    mvc:
      view:
        prefix: /
        suffix: jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*Mapper.xml
